src/App.js, src/pages/Auth/Auth.jsx
mobile screen responsive design added  and fixed logo problem it's display half only
=> login page responsive design added fixed logo half display 

src/pages/Auth/Auth.jsx
signup and  login navigation fixed 
https://github.com/user-attachments/assets/aec0a919-6309-4eed-9401-82b09b5a3bbc
=> signup and  login navigation

.github/workflows/greetings.yml
This is a PR that addresses the addition of a simple github greetings bot that display messages in the form of comments to the new users who raise a PR or an issue. Please add level1 and gssoc24-ext labels to the PR. Thank you. 
closes #1
=> #Add greetings bot

src/Components/NotificationModal/NotificationModal.jsx, src/Components/RightSide/RightSide.jsx
-Added an event listener to the notification icon.
-Implemented a modal component to display current notifications.
-Integrated the modal to be triggered upon clicking the notification icon.
-Added basic styling for the modal to fit the app’s UI.
=> feat:notification modal created

src/pages/Auth/Auth.jsx
**Description**  
The logo on the sign-up page is cut off at the bottom, impacting the overall user interface.
**Related Issue**  
Fixes [#3](https://github.com/SwanandD121/FeatherPerfect_fe/issues/3).
**Changes Made**  
- **Updated UI**: Adjusted the layout of the authentication page to enhance user experience.
- **Improved Heading Styles**: Reduced the font size and spacing of the `<h1>` element for better alignment and to prevent excessive space usage.
**Testing Instructions**  
Navigate to the sign-up page to verify that the logo is now fully visible.
=> [FIX] login page logo full not visible #3

src/App.css, src/Components/Posts/Posts.jsx
Implemented feature of  Scroll bar as discussed in issue #27.
- Modified Posts component.
- Modified App.css
Closes #27
=> Implemented feature Scroll view

src/Components/LogoSearch/LogoSearch.jsx
Hi,
I have made an enhancement to the explore input to ensure it has a more consistent width, similar to the profile input as discussed in issue #67 
Please assign me and label this as "hacktoberfest-accepted" would be greatly appreciated!
Thanks!
after:
=> Update explore input & Improve UI

README.md
=> Addition of All Contributors | Issue #62

src/pages/Auth/Auth.jsx
solved #69 
video preview (sorry for low quality)
https://github.com/user-attachments/assets/6c9f5159-a033-43f6-8782-adb04ec145b2
=> added password validation

src/App.js, src/Components/InfoCard/InfoCard.jsx
Issue has been fixed.
Redirected page :
Closes #9
=> Logout not redirecting to login page

src/pages/Auth/Auth.jsx
@SwanandD121 
please add gssoc-ext and hacktoberfest-accepted labels
=> Fixes #88: replace hyperlink with a toggle button to switch between light mode and dark mode

src/Components/ProfileCard/ProfileCardH.jsx
This PR fixes the scroll-to-top bug and allows user to see the profile page from top.
Fixed : #100 
- Bug fix (non-breaking change which fixes the issue)
- Go to Homepage
- Click on View Profile Button
This will be the ideal view from top when user will click on view profile button.
=> [FIX] : Profile Page Scroll Issue Fixed

src/pages/Auth/Auth.jsx
have added a toast when user do log in as discusses in issue #51
=> Added logged in message

src/Components/Post/Post.jsx
This pull request introduces the following features to enhance the post functionality in the project:
- **Like/Unlike Feature**: Users can now like or unlike posts, with the like count updating dynamically.
- **Commenting System**: Users can add comments to posts. Comments will be displayed below each post without hyphens.
- Added state management for likes and comments using React hooks.
- Implemented event handlers for liking, commenting, and sharing posts.
- Updated the user interface to display likes and comments clearly.
1. Click the like button to toggle the like status.
2. Add comments using the provided input field and ensure they display correctly.
3. Use the share button to test sharing functionality.
Thank you for considering my contribution!
close #104
=> added like and comment fucntionality

src/Components/NotificationModal/NotificationCard.jsx, src/Components/NotificationModal/NotificationModal.jsx
This PR adds the feature to display notification inside the notification modal.
Fixed : #101 
- Feature Addition
- Login
- Go to Homepage
- Click on Bell Icon
The modal will be opened with notification displayed.
=> [FEAT] ; Notifications Message UI Added

src/Components/RightSide/RightSide.jsx, src/Components/SettingsModal/SettingsModal.css, src/Components/SettingsModal/SettingsModal.jsx
SettingsModal has been built.
Closes #89
=> [enhancement]: Settings Page Development

src/pages/Auth/Auth.jsx
Fixes #130 Adding email field in signup form.
@SwanandD121 Please review it and merge accordingly
=> BUG: Email field added in Signup form

src/Components/FollowersCard/FollowersCard.jsx, src/Components/ProfileCard/ProfileCardH.jsx, src/Components/ProfileCard/ProfileCardP.jsx, src/Components/ProfileLeft/ProfileLeft.jsx, src/Components/ProfileSide/ProfileSide.jsx, src/pages/Profile/Profile.jsx
This PR solves issue #61. It introduces enhancements to the user profile components by implementing a persistent following count feature. The following count is now saved in localStorage, ensuring that it remains unchanged across page navigations and refreshes.
https://github.com/user-attachments/assets/dcefe04f-dc54-4a14-9c09-469a55c27d74
=> Issue #61 BUG: "Follow" button is not working solved

README.md
=> Update for Hacktoberfest

LICENSE, README.md
- Issue #127 
This is how the **Team Section** is looking for you:
This is the updated Contributors Mention section:
This is the LICENSE for your file:
=> Modified README.md file & Created LICENSE File for project

package-lock.json, package.json, src/Components/ExperienceModal/ExperienceModal.jsx
Added a new feature to add emojis in text while sharing an experience.
Fixes : #124 
- Feature Addition.
- Login
- Go to Homepage
- Click on Share Experience
As shown in image attached.
=> [FEAT] : Emojis Can Be Used While Sharing Experience 

src/Components/PostShare/PostShare.jsx
As discussed in issue #149 ,I have implemented the Conditional Logic for Content Sharing .
=> Added Conditional Logic for Content Sharing in PostShare Component

src/Components/ProfileCard/ProfileCardH.jsx
Added icons in profile card
Fixes #157 
- Bug Fix
- Login
- Go to Homepage
As shown in image attached.
=> [FIX] : Added Icons In Profile Card Improving UI & Readability
